# Configuration variables
DOMAIN_AGE_THRESHOLD = 360
THRESHOLD_SUBDOMAINS = 1
LEVENSHTEIN_THRESHOLD = 3
REDIRECT_THRESHOLD = 2

# Scores: Each feature is assigned a score based on its importance in phishing detection.
SCORE_DOMAIN_AGE = - 5
SCORE_VALID_SSL_CERTIFICATE = - 10
SCORE_SPECIAL_CHARACTERS = 15
SCORE_SUBDOMAINS = 10
SCORE_IP_ADDRESS = 10
SCORE_DYNAMIC_DNS = 5
SCORE_SIMILAR_TO_OTHER_DOMAIN = 100
SCORE_REDIRECTS = 5
SCORE_SENSITIVE_FORMS = 15

SCORE_MAX_THRESHOLD = 15